### ISSUE TITLE
[메인페이지 네비바] 네비바 라우팅 경로를 어떻게 잡아줘야할지 모르겠음  

### ISSUE THREAD

**Issue by hxxzxx** [INU-CapstoneDesign/INU-Festival-FE#40]
# 해결햐려는 문제가 무엇인가요? 🤔

네비바 각각 요소에다가 페이지를 연결시켜 색깔 변화를 하게하고싶음
 
# 어떻게 시도하고 있나요? 🔑

routes라는 파일에다가 경로를 잡아줘야하는데 App.js 가 루트, 그 children이 Nav?.. 근데 그 아래 각각 home과 map과 등등 다양한 요소가 있는데 이걸 경로를 어떻게 잡아줘야할지 감이 안잡힘
## Attachment 📸

- 이번 ISSUE의 Front 동작의 이해를 돕는 GIF 파일 첨부!

**Comment by kaori-killer** [comment]
해결했습니다.
